name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'Prepare'
  displayName: 'Prepare'
  jobs:
  - job: 'Prepare'
    displayName: 'Prepare'
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '0.12.3'
